QuickSal/QuickSal.Web/ViewModels/DebitNote/DebiNoteViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuickSal.Web.ViewModels.DebitNote
{
    public class DebiNoteViewModels
    {
  

    }
}

QuickSal/QuickSal.Web/ViewModels/DebitNote/DebitNoteVM.cs
using QuickSal.DataAcces.Contexts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuickSal.Web.ViewModels.DebitNote
{
    public class DebitNoteVM : TblDebitNote
    {
        public IEnumerable<TblDebitNote> tblDebitNotes { get; set; }
        public IEnumerable<TblDebitNoteRow> tblDebitNoteRows { get; set; }
        public IQueryable<TblSuppliers> Supplier { get; set; }
        public TblPurchaseOrder PurchaseOrders { get; set; }
        public TblDebitNote DebitNotes { get; set; }
        public TblSuppliers Supplierer { get; set; }

        public TblBusiness TblBusiness { get; set; }
    }
}

QuickSal/QuickSal.Web/Controllers/DebitNoteController.cs
namespace QuickSal.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using QuickSal.DataAcces.Contexts;
    using QuickSal.DataAcces.Models;
    using QuickSal.Services;
    using QuickSal.Web.Infraestructure.Security;
    using QuickSal.Web.ViewModels.DebitNote;
    using QuickSal.Web.ViewModels.Purchase;
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    public class DebitNoteController : Controller
    {

        private IServiceError serviceError;
        private ISecurityService securityService;
        private IAccountingService accountingService;
        private ISupplierService supplierService;
        private IInventoryService inventoryService;
        private IGlobalService globalService;
        private IBusinessService businessService;


        public DebitNoteController(IServiceError serviceError, ISecurityService securityService, IAccountingService accountingService, ISupplierService supplierService, IInventoryService inventoryService, IGlobalService globalService, IBusinessService businessService)
        {
            this.serviceError = serviceError;
            this.securityService = securityService;
            this.accountingService = accountingService;
            this.supplierService = supplierService;
            this.inventoryService = inventoryService;
            this.globalService = globalService;
            this.businessService = businessService;
        }


        /// <summary>
        /// Metodo para mostrar el listado de nota de debito
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public IActionResult ListDebitNote()
        {
            var session = securityService.GetSession();
            DebitNote model = new DebitNote();

            model.DebitNotes = supplierService.ListDebitNote(session.BranchOfficeId).OrderByDescending(x => x.DocumentEstatusId);

            return View(model);
        }

        /// <summary>
        /// Metodo para mostrar la nota de debito
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public IActionResult GetDebitNoteDetails()
        {
            var session = securityService.GetSession();
            DebitNoteVM model = new DebitNoteVM();

            //model.tblDebitNotes = inventoryService.GetDebitNote(session.BranchOfficeId);

            return View(model);
        }


        /// <summary>
        /// Metodo para mostrar el listado de PurchaseOrder
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public IActionResult GetListPurchaseOrder()
        {

            try
            {
                PurchaseViewModel Model = new PurchaseViewModel();
                var session = securityService.GetSession().BranchOfficeId;
                var branchOfficeId = Convert.ToInt64(session);
                Model.PurchaseOrders = supplierService.PurchaseOrders(branchOfficeId).Where(x => x.DocumentEstatusId == (int)DataAcces.QuickSalEnum.DocumentEstatus.Aprobada && x.Balance > 0);
                return View(Model);
            }
            catch (Exception ex)
            {
                serviceError.LogError(ex.Message, "PurchaseOrdersList", "PurchaseOrdersController", "Tuvimos un problema cargar listado de ordenes.");
                return null;
            }

        }

        /// <summary>
        /// Metodo para cargar la vista para el actualizar las notas de debito
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public IActionResult CreateDebitNote(int Id)
        {
            try
            {
                var session = securityService.GetSession().BusinessId;
                var bussineId = Convert.ToInt64(session);
                DebitNoteVM Model = new DebitNoteVM();

                Model.PurchaseOrder = supplierService.GetPurchase(Id, bussineId);
                Model.TblBusiness = businessService.GetBusinessById(bussineId);
                Model.Supplierer = supplierService.GetSuppliers(bussineId).FirstOrDefault();

                return View(Model);

            }
            catch (Exception ex)
            {
                serviceError.LogError(ex.Message, "EditPurchaseOrder", "PurchaseOrderController", "Tuvimos un problema al cargar los datos de la orden.");
                return null;
            }
        }

        /// <summary>
        /// Metodo para Crear la nota de debito
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public async Task<IActionResult> CreateDebitNoteSave(TblDebitNote debitNote, string tipoProceso)
        {
            try

            {
                var sesion = securityService.GetSession();
                var respuesta = supplierService.CreateDebitNote(debitNote, tipoProceso);
                if (respuesta.ExecutedSuccesfully)
                {
                    var task = await supplierService.Savechanges();

                    if (task.ExecutedSuccesfully & tipoProceso == "Procesar")
                        task.ExecutedSuccesfully = supplierService.AddNcfDebitNote(sesion.BranchOfficeId, debitNote.Id);
                    return Json(new
                    {
                        message = ((serviceError.TaskStatus().ExecutedSuccesfully) ? "Nota de debito registrada correctamente" : serviceError.TaskStatus().MessageList[0]),
                        status = serviceError.TaskStatus().ExecutedSuccesfully,
                        redirect = Url.Action("ListDebitNote")

                    });
                }
                else
                {
                    return Json(new
                    {
                        message = ((serviceError.TaskStatus().ExecutedSuccesfully) ? respuesta.Messages() : serviceError.TaskStatus().MessageList[0]),
                        status = serviceError.TaskStatus().ExecutedSuccesfully,
                    });
                }
            }
            catch (Exception ex)
            {
                serviceError.LogError(ex.Message, "CreateDebitNoteSave", "DebitNoteController", "Tuvimos un problema al registrar la nota.");
                return Json(new
                {
                    message = ((serviceError.TaskStatus().ExecutedSuccesfully) ? "" : serviceError.TaskStatus().MessageList[0]),
                    status = serviceError.TaskStatus().ExecutedSuccesfully
                });
            }
        }

        /// <summary>
        /// Metodo para cargar la vista para el actualizar las notas de debito
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public IActionResult EditDebitNote(int Id)
        {
            try
            {
                var session = securityService.GetSession();
                var branchOfficeId = Convert.ToInt64(session.BranchOfficeId);
                DebitNoteVM Model = new DebitNoteVM();

                Model.DebitNotes = supplierService.DebitNoteDetails(Id);
                Model.Supplierer = supplierService.GetSuppliers(Convert.ToInt64(session.BusinessId)).Where(x => x.Id == Model.DebitNotes.SuppliersId).FirstOrDefault();
                ViewBag.PurchaseOrders = supplierService.PurchaseOrdersId(branchOfficeId, Model.DebitNotes.PurchaseOrderId).FirstOrDefault().DocumentNumber;

                //Cargamos las opciones desplegables
                return View(Model);

            }
            catch (Exception ex)
            {
                serviceError.LogError(ex.Message, "EditPurchaseOrder", "PurchaseOrderController", "Tuvimos un problema al cargar los datos de la orden.");
                return null;
            }
        }

        /// <summary>
        /// Metodo para cargar el modal que contiene el detalle de la orden de compra
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ServiceFilter(typeof(LoginSecurityFilter))]
        public IActionResult ModalPurchOrder()
        {
            return View();
        }
        /// <summary>
        /// Metodo  actualizar las notas de debito en la base datos
        /// </summary>
        /// <returns></returns>
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public JsonResult UpdatedebitNote(TblDebitNote tblDebitNote, int tipoProceso)
        {
            try
            {
                var session = securityService.GetSession().BusinessId;
                var respuesta = supplierService.UpdateDebitNote(tblDebitNote, tipoProceso);

                return Json(new
                {
                    message = ((serviceError.TaskStatus().ExecutedSuccesfully) ? "Nota de debito actualizada correctamente" : serviceError.TaskStatus().MessageList[0]),
                    status = serviceError.TaskStatus().ExecutedSuccesfully,
                    redirect = Url.Action("ListDebitNote")

                });                
          
            }
            catch (Exception ex)
            {
                serviceError.LogError(ex.Message, "UpdatedebitNote", "DebitNoteController", "Tuvimos un problema al actualizar la nota.");
                return Json(new
                {
                    message = ((serviceError.TaskStatus().ExecutedSuccesfully) ? "" : serviceError.TaskStatus().MessageList[0]),
                    status = serviceError.TaskStatus().ExecutedSuccesfully
                });
            }
        }


        /// Metodo para cargar el detalle de la orden
        /// </summary>
        /// <returns></returns>       
        [ServiceFilter(typeof(LoginSecurityFilter))]
        public JsonResult GetPurchaseOrder(long PurchaseId = 0)
        {

QuickSal/QuickSal.Web/Views/DebitNote/CreateDebitNote.cshtml
@model QuickSal.Web.ViewModels.DebitNote.DebitNoteVM
@{
    ViewData["Title"] = "Registro de Nota de Debito";
    Layout = "~/Views/Shared/Dashboard/_Layout.cshtml";

    QuickSal.Web.Api.GenericController genericController = new QuickSal.Web.Api.GenericController();
}


<div class="panel panel-flat">
    @*<div class="panel-heading">
            <h5 class="panel-title">
                Registro  Nota de Débito
                <a class="heading-elements-toggle">

                    <i class="icon-more"></i>
                </a>
            </h5>
        </div>*@



    <div class="panel-body">
        <div class="invoice overflow-auto">
            <form id="Edit-PurchaseOrder">
                <div style="min-width: 600px">
                    <main>
                        <div class="row contacts">
                            <div class="col-md-6 col-xs-6 invoice-to">
                                <div class="text-gray-light"> <strong>Factura de Nota de Debito a:</strong></div>
                                <h5 class="to">@Model.Supplierer.Code</h5>
                                <h2 class="to">@Model.Supplierer.Names.ToUpper()</h2>
                                <div class="address">@Model.Supplierer.AddressSuppliers</div>
                                <div class="address">Tel: @Model.Supplierer.PhoneNumber</div>
                                <div class="email"><a href="mailto:@Model.Supplierer.Email">@Model.Supplierer.Email</a></div>
                            </div>

                            <div class="col-md-6 col-xs-6 invoice-details">
                                <h2 class="invoice-id">
                                    Factura de compras:
                                    <i class="icon-cart-remove"></i>
                                    <label id="documentNumber"></label>
                                </h2>
                                <table align="right">
                                    <tr>
                                        <td>Fecha documento:</td>
                                        <td>
                                            <div class="input-group">
                                                <input type="text" class="date" value="@Model.PurchaseOrder.CreateDate.ToString("dd/MM/yyy")" id="DocumentDate" disabled>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Fecha vencimiento:</td>
                                        <td>
                                            <div class="input-group">
                                                <input type="text" class="date" value="@Model.PurchaseOrder.ExpirationDate" id="ExpirationDate" disabled>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>NCF Modificado:</td>
                                        <td>
                                            <input type="text" class="thin-input fab-label-right" value="@Model.PurchaseOrder.Ncf" name="Ncfmodified" readonly>
                                        </td>
                                    </tr>
                                </table>
                                <div class="tab-pane active" id="left-icon-tab1">
                                    <div hidden>
                                        <div class="form-group">
                                            <input type="text" value="@Model.PurchaseOrder.Id" name="PurchaseOrderId" class="form-control">
                                            <input value="@Model.PurchaseOrder.BranchOfficeId" name="BranchOfficeId" />
                                            <input value="@Model.PurchaseOrder.SuppliersId" name="SuppliersId" />
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="tabbable">

                            <div class="tab-content">
                                <div class="panel-primary">

                                    <div class="panel-body">
                                        <button type="button" id="BtnCreate" class="btn border-slate text-slate-800 btn-flat pull-left btn-icon callModal"><i class="icon-folder-plus"></i></button>

                                        <div class="col-lg-12 col-sm-12- col-md-12 col-xs-12">
                                            @* Esta es la tabla que hace referencia desde el javascipt*@
                                            <table id="PurchaseTable" class="display" style="width:100%"></table>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-xs-6">
                                <div class="notices">
                                    <div>Observación:</div>
                                    <div class="notice">
                                        <textarea type="text" placeholder="Observación" id="Observation" rows="5" name="Observation" class="form-control"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 col-xs-6">
                                <table class="tfooter">
                                    <tr>
                                        <td colspan="2"></td>
                                        <td colspan="2">SubTotal</td>
                                        <td id="mensaje">0.00</td>
                                    </tr>
                                    <tr>
                                        <td colspan="2"></td>
                                        <td colspan="2">Impuesto</td>
                                        <td id="Mensajetax">0.00</td>
                                    </tr>
                                    <tr>
                                        <td colspan="2"></td>
                                        <td colspan="2">Descuento</td>
                                        <td id="descuentoTotal">0.00</td>
                                    </tr>
                                    <tr style="display:none">
                                        <td colspan="2"></td>
                                        <td colspan="2">
                                            <i class="icon-file-plus"></i> Crédito
                                        </td>
                                        <td>
                                            <i class="icon-minus2"></i>
                                            <span id="PendingBalanceTotal">0.00</span>
                                            <i class="icon-bin cursor" id="removePendigBalance"></i>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2"></td>
                                        <td colspan="2">Total</td>
                                        <td id="MensajeTotal">0.00</td>
                                    </tr>
                                </table>
                                <div hidden>
                                    <input id="Subtotal" value="" name="SubTotal" />
                                    <input id="total" value="" name="Total" />
                                </div>
                            </div>
                        </div>
                    </main>
                </div>

            </form>
        </div>
    </div>

<div class="panel-footer">
    <div class="col-md-12">
        <div class="pull-right">
            <div class="col-md-6 col-xs-6">
                <a href="@Url.Action("ListDebitNote", "DebitNote")" id="BtnCancelar" class="btn border-slate text-slate-800 btn-flat back">
                    <i class="icon-cross2 position-left"></i> Cancelar
                </a>
            </div>

            <div class="col-md-6 col-xs-6">
                <div class="dropdown">
                    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <i class="icon-check position-left"></i> Aceptar
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li>
                            <a href="#" class="save" id="Enviar" data-document="@((int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Proceso)">
                                <i class="icon-floppy-disk"></i> Guardar
                            </a>
                        </li>
                        <li>
                            <a href="#" class="save" id="Procesar" data-document="@((int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Aprobada)">
                                <i class="icon-checkmark4"></i> Registrar
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
   </div>
</div>
@section scripts{
    <script src=@Url.Content("~/Scripts/Dashboard/DebitNote/DebitNote.js")></script>
    <script src="~/Scripts/Dashboard/DebitNote/CreateScript.js"></script>
}

QuickSal/QuickSal.Web/Views/DebitNote/GetDebitNoteDetails.cshtml
@model QuickSal.Web.ViewModels.DebitNote.DebitNoteVM
@{
    ViewData["Title"] = "EditDebitNote";
    Layout = "~/Views/Shared/Dashboard/_Layout.cshtml";
    QuickSal.Web.Api.GenericController genericController = new QuickSal.Web.Api.GenericController();
}

<div class="panel panel-flat row">
    <div class="panel-heading">
        <h5 class="panel-title ">
            Editar Nota de Debito
            <a class="heading-elements-toggle">
                <i class="icon-more"></i>
            </a>
        </h5>
        <div>
            @if (Model.PurchaseOrder.DocumentEstatusId == (int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Aprobada)
            {
                <span class="label label-success">Aprobada</span>
            }
            else if (Model.PurchaseOrder.DocumentEstatusId == (int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Proceso)
            {
                <span class="label label-info">Proceso</span>
            }
            else if (Model.PurchaseOrder.DocumentEstatusId == (int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Anulada)
            {
                <span class="label label-danger">Anulada</span>
            }

        </div>
    </div>
    <div class="panel-body ">
        <div class="tabbable">
            <form id="Edit-PurchaseOrder">
                <div class="tab-content">
                    <div hidden>
                        <div class="form-group">
                            <input type="text" value="@Model.PurchaseOrder.Id" name="PurchaseOrder.Id" class="form-control">
                        </div>
                    </div>
                    <div>
                        <div>
                            <label><strong>@Model.TblBusiness.Name</strong></label>
                        </div>
                        <div>
                            <label>@Model.TblBusiness.Description</label>
                        </div>
                        <div>
                            <label>@Model.TblBusiness.Description</label>
                        </div>
                    </div>
                    <div class="form-line">
                        <div class=" col-md-offset-8 col-md-3">
                            <div class=" col-md-offset-9">
                                <label><strong>No. Documento</strong></label>
                            </div>
                            <div class=" col-md-offset-9">
                                <label> <strong>Fecha</strong></label>
                            </div>
                            <div class=" col-md-offset-9">
                                <label> <strong>No. Orden</strong></label>
                            </div>
                            <div class=" col-md-offset-9">
                                <label><strong>NFC Nodifica</strong></label>
                            </div>
                            <div class=" col-md-offset-9">
                                <label><strong>NFC Nodifica</strong></label>
                            </div>
                        </div>
                        <div class="form-group col-md-offset-5 ">
                            <div class="col-md-offset-10">
                                <label>@Model.PurchaseOrder.DocumentNumber</label>
                            </div>
                            <div class="col-md-offset-10">
                                <label>@Model.PurchaseOrder.CreateDate.ToString("dd/MM/yyy")</label>
                            </div>
                            <div class=" col-md-offset-10">
                                <label>@Model.PurchaseOrder.Id</label>
                            </div>
                            <div class=" col-md-offset-10">

                                <label>@Model.PurchaseOrder.Ncf</label>
                            </div>
                            <div class=" col-md-offset-10">
                                <label>@Model.PurchaseOrder.Ncf</label>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-primary">
                        <div class="panel-body">

                            <div col-lg-12 col-sm-12- col-md-12 col-xs-12>
                                <!--Esta es la tabla que hace referencia desde el javascipt-->
                                <table id="PurchaseTable" class="display" style="width:100%"></table>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-offset-0 ">
                        <div class="form-group">
                            <label>Observacion</label>
                        </div>
                        <textarea></textarea>
                    </div>
                    <div class=" col-md-offset-7 col-md-4">
                        <div class=" col-md-offset-9">
                            <label><strong>Sub-Total Orden: RD$</strong></label>
                        </div>
                        <div class=" col-md-offset-9">
                            <label><strong>Total Descuento: RD$</strong></label>
                        </div>
                        <div class=" col-md-offset-9 ">
                            <label><strong>Total Impuesto: RD$ </strong></label>
                        </div>
                        <div class=" col-md-offset-9">
                            <label><strong>Total Orden: RD$    </strong></label>
                        </div>
                    </div>
                    <div class="form-group col-md-offset-6 ">
                        <div class=" col-md-offset-10">
                            <label id="mensaje">@Model.PurchaseOrder.SubTotal.ToString("N2")</label>
                        </div>
                        <div class=" col-md-offset-10">
                            <labe id="MensajeDescuento">@Model.PurchaseOrder.Discount.ToString("N2")</labe>
                        </div>
                        <div class=" col-md-offset-10">
                            <labe id="Mensajetax">@Model.PurchaseOrder.TotalTax.ToString("N2")</labe>
                        </div>
                        <div class=" col-md-offset-10">

                            <label id="MensajeTotal">@Model.PurchaseOrder.Total.ToString("N2")</label>
                        </div>
                    </div>
                    <input id="mensajesubtotal" name="PurchaseOrder.SubTotal" value="@Model.PurchaseOrder.SubTotal" hidden /><br />
                    <input id="Descuentototal" name="PurchaseOrder.Discount" value="@Model.PurchaseOrder.Discount" hidden><br />
                    <input id="taxtotal" name="PurchaseOrder.TotalTax" value="@Model.PurchaseOrder.TotalTax" hidden /><br />
                    <input id="Totaltotal" name="PurchaseOrder.Total" value="@Model.PurchaseOrder.Total" hidden /><br />
                </div>
                <div style="text-align:center;">
                    <table class="table" style="margin: 20px auto;">
                        <thead>
                            <tr>
                                <th style="text-align: right">
                                </th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </form>
        </div>
    </div>

    <div class="panel-footer">
        <div class="col-md-12">
            <div class="pull-right">
                <a href="@Url.Action("GetDebitNote", "DebitNote")" class="btn btn-danger">
                    <i class="icon-cross2 position-left"></i>
                    <span>Cancelar</span>
                </a>

                @if (Model.PurchaseOrder.DocumentEstatusId == (int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Proceso)
                {
                    <div class="btn-group dropup">
                        <button type="button" class="btn  btn-primary"><b><i class="icon-cog5 position-left"></i></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Acción</font></font></button>
                        <button type="button" class="btn bg-create dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <button id="Enviar" class="btn border-slate text-slate-800 btn-flat pull-center col-md-12" data-document="@((int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Proceso)">
                                    <i class="icon-checkmark4 position-left"> Guardar  Orden  </i>
                                </button>
                            </li>
                            <li>
                                <button id="Procesar" class="btn border-slate text-slate-800 btn-flat pull-center col-md-12" data-document="@((int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Aprobada)">
                                    <i class="icon-checkmark4 position-left"> Procesar  Orden  </i>
                                </button>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src=@Url.Content("~/Scripts/Dashboard/DebitNote/DebitNote.js")></script>

}

QuickSal/QuickSal.Web/Views/DebitNote/ModalPurchOrder.cshtml
@{
    ViewData["Title"] = "Listado de orden de compra";
}



<div col-lg-12 col-sm-12- col-md-12 col-xs-12>
    <!--Esta es la tabla que hace referencia desde el javascipt-->
    <table class="datatable display ItemList" id="ModalPurchaseTable" style="width:100%"></table>
</div>




    <div class="text-center">
        <span class="alert-primary">Seleccione el o los productos que desea agregar a la <strong>Nota de Debito</strong></span>
    </div>



@section scripts{
    <script src=@Url.Content("~/Scripts/Dashboard/DebitNote/CreateScript.js")></script>

}