QuickSal/QuickSal.Web/ViewModels/VendorPayment/VendorPaymentRowVM.cs
using QuickSal.DataAcces.Contexts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuickSal.Web.ViewModels.VendorPayment
{
    public class VendorPaymentRowVM : TblVendorPaymentRow
    {
        public IQueryable<TblVendorPaymentRow> TblVendorPaymentRow { get; set; }
    }
}

QuickSal/QuickSal.Web/ViewModels/VendorPayment/VendorPaymentViewModel.cs
using QuickSal.DataAcces.Contexts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuickSal.Web.ViewModels.VendorPayment
{
    public class VendorPaymentViewModel
    {
        public long Id { get; set; }
        public long BranchOfficeId { get; set; }
        public long EmployeeBusinessId { get; set; }
        public byte DocumentEstatusId { get; set; }
        public string DocumentNumber { get; set; }
        public string fecha { get; set; }

        public DateTime CreateDate { get; set; }
        public DateTime UpdateDate { get; set; }
        public string Observation { get; set; }
        public decimal Total { get; set; }
        public long EmployeeCreateId { get; set; }
        public long EmployeeModifyId { get; set; }
        public long VendorPaymentId { get; set; }
        public long SuppliersId { get; set; }
        public long PurchaseOrderId { get; set; }
        public string PurchaseOrderDocument { get; set; }
        public string SupplierName { get; set; }
        public string Concept { get; set; }
        public string Owed { get; set; }
        public string PaidOut { get; set; }
        public string Payment { get; set; }
        public string Pending { get; set; }
        public string Delete { get; set; }
        public TblBranchOffice BranchOffice { get; set; }
        public TblEmployeeBusiness EmployeeBusiness { get; set; }
        public TblVendorPayment  VendorPayment { get; set; }
        public IQueryable<TblVendorPayment> ListVendorPayment { get; set; }
        public ICollection<TblVendorPaymentRow> TblVendorPaymentRow { get; set; }
    }
}

QuickSal/QuickSal.Web/Controllers/VendorPaymentController.cs
 using Microsoft.AspNetCore.Mvc;
using QuickSal.DataAcces.Models;
using QuickSal.Services;
using QuickSal.Web.Infraestructure.Security;
using QuickSal.Web.ViewModels.Purchase;
using QuickSal.Web.ViewModels.VendorPayment;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuickSal.Web.Controllers
{
    public class VendorPaymentController : Controller
    {
        private readonly IServiceError serviceError;
        private readonly ISecurityService SecurityService;
        private readonly IAccountingService accountingService;
        private readonly ISupplierService supplierService;
        private readonly IInventoryService inventoryService;
        private readonly IGlobalService globalService;
        public VendorPaymentController(IServiceError serviceError, ISecurityService SecurityService, IAccountingService accountingService, ISupplierService supplierService, IInventoryService inventoryService, IGlobalService globalService)
        {
            this.serviceError = serviceError;
            this.SecurityService = SecurityService;
            this.accountingService = accountingService;
            this.supplierService = supplierService;
            this.inventoryService = inventoryService;
            this.globalService = globalService;
        }

        [HttpGet]
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public IActionResult VendorPaymentList()
        {
            try
            {
                VendorPaymentViewModel Model = new VendorPaymentViewModel();
                //long session = SecurityService.GetSession().BusinessId;
                //long bussined = Convert.ToInt64(session);
                var session = SecurityService.GetSession();
                Model.ListVendorPayment = supplierService.GetVendorPayment(session.BranchOfficeId);
                return View(Model);
            }
            catch (Exception ex)
            {
                serviceError.LogError(ex.Message, "VendorPaymentList", "VendorPaymentController", "Tuvimos un problema cargar listado de Pagos.");
                return null;
            }
        }

        /// <summary>
        /// Metodo para cargar la vista de registro de ncf
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public IActionResult _OrdenCompraList()
        {
            try
            {
                PurchaseViewModel Model = new PurchaseViewModel();
                var session = SecurityService.GetSession();
                Model.PurchaseOrders = supplierService.VendorPurchaseOrders(session.BranchOfficeId);
                ////Obtenemos un nuevo codigo para el cliente
                //string code = supplierService.GetLastVendorPayment(bussined);
                //ViewBag.VendorPayment = globalService.GenerateCode(Services.Support.EnumTypes.CodeEntities.VendorPayment, code);

                return View(Model);
            }
            catch (Exception ex)
            {
                serviceError.LogError(ex.Message, "PurchaseOrdersList", "PurchaseOrdersController", "Tuvimos un problema cargar listado de ordenes.");
                return null;
            }
        }

        // GET: VendorPayment
        [HttpGet]
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public IActionResult VendorPaymentCreate(string data)
        {

            List<string> listado = data.Split(',').ToList();
            IEnumerable<long> datos = listado.Select(long.Parse);

            VendorPaymentRowVM vendorPayment = new VendorPaymentRowVM();
            long session = SecurityService.GetSession().BusinessId;
            long bussined = Convert.ToInt64(session);
            vendorPayment.TblVendorPaymentRow = supplierService.PurchaseRow(bussined, datos);

            try
            {
                ViewBag.Fecha = DateTime.Now;
                return View(vendorPayment);
            }
            catch (Exception ex)
            {
                serviceError.LogError(ex.Message, "VendorPaymentCreate", "VendorPaymentController", "Tuvimos un problema cargar listado de Pagos.");
                return null;
            }
        }

        // GET: VendorPayment
        /// Metodo para cambiar el estado del PurchaseOrder
        /// </summary>
        /// <returns></returns>
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public JsonResult StatusPayment(int Id, long DocumentStatusID)
        {
            try
            {
                long bussineId = SecurityService.GetSession().BusinessId;
                DataAcces.Models.TaskResult task = supplierService.SetVendorPaymentstatus(Id, bussineId, DocumentStatusID);
                if (task.ExecutedSuccesfully)
                {
                    supplierService.Savechanges();

                }
                return Json(new
                {
                    message = ((serviceError.TaskStatus().ExecutedSuccesfully) ? "Pagos de orden guardada correctamente" : serviceError.TaskStatus().MessageList[0]),
                    status = serviceError.TaskStatus().ExecutedSuccesfully,
                    redirect = Url.Action("VendorPaymentList")
                });

            }
            catch (Exception)
            {
                //serviceError.LogError(ex.Message, "StatusPurchaseOrder", "PurchaseOrderController", "Tuvimos un problema al " + ((DocumentStatusID) ? "activar" : "Desactivar") + " el Ncf.");
                return Json(new
                {
                    message = ((serviceError.TaskStatus().ExecutedSuccesfully) ? "" : serviceError.TaskStatus().MessageList[0]),
                    status = serviceError.TaskStatus().ExecutedSuccesfully
                });
            }
        }

        [ServiceFilter(typeof(LoginSecurityFilter))]
        public JsonResult GetVendorPayment(long PurchaseId = 0)
        {
            long session = SecurityService.GetSession().BusinessId;
            long bussineId = Convert.ToInt64(session);
            //Luego verifica los campos que retornar que te estan dando error
            IEnumerable<VendorPaymentViewModel> PurchaseList = supplierService.GetVendorPaymentRow(PurchaseId).Select(x => new VendorPaymentViewModel
            {
                Id = x.Id,
                VendorPaymentId = x.VendorPaymentId,
                SuppliersId = x.SuppliersId,
                PurchaseOrderId = x.PurchaseOrderId,
                PurchaseOrderDocument = x.PurchaseOrderDocument,
                SupplierName = x.SupplierName,
                Concept = x.Concept,
                Owed = x.Owed.ToString("N2"),
                PaidOut =x.PaidOut.ToString("N2"),
                Payment = x.Payment.ToString("N2"),
                Pending = x.Pending.ToString("N2"),
                Delete = "<ul class=\"icons-list\"><li class=\"dropdown\"><a href = \"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"icon-menu9\"></i></a><ul class=\"dropdown-menu dropdown-menu-right\"><li><a type=\"button\" class=\"btn btn-default btn-icon modificarProducto\" data-id=\"" + x.Id + "\" ><i class=\"icon-pencil6\"></i>Editar</a><a type=\"button\" class=\"btn btn-default btn-icon deleteRow\"><i class=\"icon-trash\"></i>Eliminar</a></ul></li></ul>",
            });

            //
            return Json(new
            {
                prices = globalService.ConvertToArray(PurchaseList,
                new string[] { "Id", "VendorPaymentId", "PurchaseOrderId", "SuppliersId", "PurchaseOrderDocument", "SupplierName", "Concept", "Owed", "PaidOut", "Payment", "Pending", "Delete" })
            });
        }

        [HttpGet]
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public IActionResult _EditVendorPayment(int Id)
        {
            try
            {
                long session = SecurityService.GetSession().BusinessId;
                long bussineId = Convert.ToInt64(session);
                VendorPaymentViewModel Model = new VendorPaymentViewModel
                {
                    VendorPayment = supplierService.GetVendorPaymentId(Id, bussineId)
                };
                //Cargamos las opciones desplegables
                return View(Model);

            }
            catch (Exception ex)
            {
                serviceError.LogError(ex.Message, "EditPurchaseOrder", "PurchaseOrderController", "Tuvimos un problema al cargar los datos de la orden.");
                return null;
            }
        }

        // GET: VendorPayment/Details/5
        [HttpPost]
        [ServiceFilter(typeof(HandledSecurityFilter))]
        public async Task<JsonResult> CreateVendorPayment(VendorPaymentViewModel Model)
        {
            long session = SecurityService.GetSession().BusinessId;
            long bussined = Convert.ToInt64(session);
            string code = supplierService.GetLastVendorPayment(bussined);
            Model.VendorPayment.DocumentNumber = globalService.GenerateCode(Services.Support.EnumTypes.CodeEntities.VendorPayment, code);

            try
            {
                supplierService.VendorPaymentCreate(Model.VendorPayment);

                var task = await supplierService.Savechanges();
                if (task.ExecutedSuccesfully)
                {
                    if (Model.VendorPayment.DocumentEstatusId == 1)
                    {
                        supplierService.MovimientoPurchase(Model.VendorPayment.Id);
                    }
                }
                return Json(new
                {
                    message = ((serviceError.TaskStatus().ExecutedSuccesfully) ? "Pagos de Proveedores registrado correctamente" : serviceError.TaskStatus().MessageList[0]),
                    status = serviceError.TaskStatus().ExecutedSuccesfully,
                    redirect = Url.Action("VendorPaymentList")
                });
            }
            catch (Exception ex)
            {

QuickSal/QuickSal.Web/Views/VendorPayment/EditVendorPaymentRow.cshtml
@{
    ViewData["Title"] = "EditVendorPaymentRow";
    Layout = null;
}

<div class="panel-body">
    <div class="tabbable">

        <form id="Edit-VendorPaymentRow">
            <div class="tab-content">
                <div class="tab-pane active" id="left-icon-tab1">

                    <div hidden>
                        <div class="form-group">
                            <input type="text" value="" id="NoDocument" class="form-control">
                            <input type="text" value="" id="index" class="form-control">
                            <input type="text" value="" id="provedor" class="form-control">
                            <input type="text" value="" id="opcion" class="form-control">
                            <input type="text" value="" id="SuppliersId" class="form-control">
                            <input type="text" value="" id="PurchaseOrderId" class="form-control">
                            <input type="text" value="" id="Id" class="form-control">
                            <input type="text" value="" id="VendorPaymentId" class="form-control">

                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-12- col-md-6 col-xs-12">
                        <div class="form-group">
                            <label>Concepto: </label>
                            <input class="form-control" type="text" value="" id="concepto" />
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-12- col-md-6 col-xs-12">
                        <label>Balance:</label>
                        <div class="form-group">
                            <input class="form-control" type="text" value="" placeholder="Cantidad" id="balance" readonly>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-12- col-md-6 col-xs-12">
                        <div class="form-group">
                            <label>Pagado: </label>
                            <input class="form-control" type="text" value="" id="pagado" readonly />
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-12- col-md-6 col-xs-12">
                        <label>A Pagar:</label>
                        <div class="form-group">
                            <input class="form-control" name="aPagar" type="number" value="" placeholder="Cantidad" id="aPagar">
                            <span id="resultados" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-12- col-md-6 col-xs-12">
                        <div class="form-group">
                            <label>Pendiente: </label>
                            <input class="form-control" type="text" value="" id="pendiente" readonly/>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



@section scripts{

    <script src=@Url.Content("~/Scripts/Dashboard/VendorPayment/VendorPayment.js")></script>

}

QuickSal/QuickSal.Web/Views/VendorPayment/VendorPaymentCreate.cshtml
@model QuickSal.Web.ViewModels.VendorPayment.VendorPaymentRowVM
@{
    ViewData["Title"] = "Registro de Pagos a Proveedores";
    Layout = "~/Views/Shared/Dashboard/_Layout.cshtml";

    QuickSal.Web.Api.GenericController genericController = new QuickSal.Web.Api.GenericController();
}

<div class="panel panel-flat">
    <div class="panel-body">
        <div>
            <strong>Pagos a Proveedores</strong> <a class="heading-elements-toggle"><i class="icon-cash"></i></a>
        </div>

        <div>
            <button id="BtnCreate" type="button" class="btn border-slate text-slate-800 btn-flat pull-left"> <i class="icon-cash"></i> </button>
        </div>

        <form action="#">
            <div class="form-line col-md-12">
                <div class="col-md-6"></div>
                <div class="form-inline col-md-6 ">
                    <div class=" col-md-offset-9 col-md-4 ">
                        <div class=" ">
                            <label><strong></strong></label>
                        </div>
                        <div class="">
                            <label><strong>Fecha: </strong>@ViewBag.Fecha.ToString("dd/MM/yyyy")</label>
                            <input class="form-control" hidden="hidden" type="hidden" placeholder="descuento" name="VendorPayment.CreateDate" readonly value="@ViewBag.Fecha">
                        </div>
                    </div>
                </div>

            </div>

            <!--Esta es la tabla que hace referencia desde el javascipt-->
            <table id="PurchaseTable" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th hidden="hidden">Id</th>
                        <th hidden="hidden">SuppliersId</th>
                        <th>No.Orden</th>
                        <th>Proveedor</th>
                        <th>Concepto</th>
                        <th>Balance</th>
                        <th>Pagado</th>
                        <th>A pagar</th>
                        <th>Pendiente</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var purcha in Model.TblVendorPaymentRow)
                    {
                        <tr>
                            <td hidden="hidden">@purcha.PurchaseOrderId</td>
                            <td hidden="hidden">@purcha.SuppliersId</td>
                            <td>@purcha.PurchaseOrderDocument</td>
                            <td>@purcha.SupplierName</td>
                            <td>@purcha.Concept</td>
                            <td>@purcha.Pending.ToString("N2")</td>
                            <td>@purcha.PaidOut</td>
                            <td>@purcha.Payment</td>
                            <td>@purcha.Pending.ToString("N2")</td>


                            <td>
                                <ul class="icons-list">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <i class="icon-menu9"></i>
                                        </a><ul class="dropdown-menu dropdown-menu-right">
                                            <li>
                                                <a type="button" class="btn btn-default btn-icon modificarProducto" data-id="@purcha.Id"><i class="icon-pencil6"></i>Editar</a>
                                                <a type="button" class="btn btn-default btn-icon deleteRow"><i class="icon-trash"></i>Eliminar</a>
                                        </ul>
                                    </li>
                                </ul>

                            </td>

                        </tr>
                    }
                </tbody>
            </table>

            <div class="row">

                <div class=" col-md-6 col-xs-6">
                    <div class="notices">
                        <label>Observaciones</label>
                        <textarea placeholder="Observación" rows="5" name="VendorPayment.Observation" class="form-control" style="border-left: 6px solid #3989c6;"></textarea>
                    </div>
                </div>
                <div class="col-md-6 col-xs-6">
                    <table class="tfooter" style="float: right;">
                        <tr>
                            <td colspan="2">
                                <h1 style="color: black;"> Total $:<span id="mensaje"></span> </h1>
                                <input id="mensajesubtotal" hidden="hidden" name="VendorPayment.Total" type="text" value="" /><br />

                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </form>
</div>

<div class="panel-footer">
    <div class="col-md-12">
        <div class="pull-right">

            <div class="col-md-6 col-xs-6">
                <a href="@Url.Action("VendorPaymentList", "VendorPayment")" class="btn border-slate text-slate-800 btn-flat back">
                    <i class="icon-cross2 position-left"></i> Cancelar
                </a>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="dropdown">
                    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <i class="icon-check position-left"></i> Aceptar
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li>
                            <a href="#" id="Enviar" class="save" name="VendorPayment.DocumentEstatusId" data-document="@((int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Proceso)">
                                <i class="icon-floppy-disk"></i> Guardar
                            </a>
                        </li>
                        <li>
                            <a href="#" id="Procesar" class="save"  name="VendorPayment.DocumentEstatusId" data-document="@((int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Aprobada)">
                                <i class="icon-checkmark4"></i> Procesar
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
           
        </div>

    </div>
</div>
        
 </div>


@section scripts{
    <script src=@Url.Content("~/Scripts/Dashboard/VendorPayment/VendorPayment.js")></script>

}

QuickSal/QuickSal.Web/Views/VendorPayment/_EditVendorPayment.cshtml
@model QuickSal.Web.ViewModels.VendorPayment.VendorPaymentViewModel
@{
    ViewData["Title"] = "Edición de Pagos a Proveedores";
    Layout = "~/Views/Shared/Dashboard/_Layout.cshtml";

    QuickSal.Web.Api.GenericController genericController = new QuickSal.Web.Api.GenericController();
}

<div class="panel panel-flat">
    <div class="panel-body">
        <div>
            <strong>Pagos a Proveedores</strong> <a class="heading-elements-toggle"><i class="icon-more"></i></a>
        </div>
        <div>
            <button id="BtnCreate" type="button" class="btn border-slate text-slate-800 btn-flat pull-left"> <i class="icon-cash"></i> </button>
        </div>
        <div class="row col-md-12">
            @if (Model.VendorPayment.DocumentEstatusId == (int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Aprobada)
            {
                <span class="label label-success">Aprobada</span>
            }
            else if (Model.VendorPayment.DocumentEstatusId == (int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Proceso)
            {
                <span class="label label-info">Proceso</span>
            }
            else if (Model.VendorPayment.DocumentEstatusId == (int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Anulada)
            {
                <span class="label label-danger">Anulada</span>
            }
        </div>

        <form id="Edit-PurchaseOrder">

            <div hidden>
                <div class="form-group">
                    <input type="text" value="@Model.VendorPayment.Id" name="VendorPayment.Id" class="form-control">
                    <input type="text" value="@Model.VendorPayment.DocumentEstatusId" id="estado" class="form-control">
                </div>
            </div>

            <div class="form-line col-md-12">
                <div class="col-md-6"></div>
                <div class="form-inline col-md-6 ">
                    <div class=" col-md-offset-9 col-md-4 ">
                        <div class=" ">
                            <label><strong>No.Documento: </strong> @Model.VendorPayment.DocumentNumber</label>
                            <input class="form-control" hidden="hidden" type="hidden" placeholder="descuento" name="VendorPayment.DocumentNumber" readonly value="@Model.VendorPayment.DocumentNumber">
                        </div>

                        <div class="">
                            <label><strong>Fecha: </strong> @Model.VendorPayment.CreateDate.ToString("dd/MM/yyyy")</label>
                            <input class="form-control" hidden="hidden" type="hidden" placeholder="descuento" name="VendorPayment.CreateDate" readonly value="@ViewBag.Fecha">
                        </div>
                    </div>
                </div>
            </div>

            <!--Esta es la tabla que hace referencia desde el javascipt-->
            <table id="EditVendorPayment" class="display" style="width:100%"></table>

            <div class="row">
                <div class="col-md-6 col-xs-6">
                    <div class="notices">
                        <label>Observaciones</label><br>
                        <textarea class="form-control" placeholder="Observación" rows="5" name="VendorPayment.Observation" style="border-left: 6px solid #3989c6;">@Model.VendorPayment.Observation</textarea>
                    </div>
                </div>

                <div class="col-md-6 col-xs-6">
                    <table class="tfooter"  style="float: right;">
                        <tr>
                            <td>
                                <h1 style="color: black;"> Total:$<span id="mensaje"></span> </h1>
                                <input id="mensajesubtotal" hidden="hidden" name="VendorPayment.Total" type="text" value="" /><br />

                            </td>
                        </tr>
                    </table>
                </div>
            </div>


            <div class="panel-footer">
                <div class="col-md-12">
                    <div class="pull-right">

                        <div class="col-md-6 col-xs-6">
                            <a href="@Url.Action("VendorPaymentList", "VendorPayment")" class="btn border-slate text-slate-800 btn-flat back">
                                <i class="icon-cross2 position-left"></i> Cancelar
                            </a>
                        </div>
                        <div class="col-md-6 col-xs-6">
                            @if (Model.VendorPayment.DocumentEstatusId == (int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Proceso)
                            {

                                <div class="dropdown">
                                    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        <i class="icon-check position-left"></i> Aceptar
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                        <li>
                                            <a href="#" id="Enviar" class="save" data-document="@((int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Proceso)">
                                                <i class="icon-floppy-disk"></i> Guardar
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" id="Procesar" class="save" data-document="@((int)QuickSal.DataAcces.QuickSalEnum.DocumentEstatus.Aprobada)">
                                                <i class="icon-checkmark4"></i> Procesar
                                            </a>
                                        </li>

                                    </ul>
                                </div>

                            }

                        </div>

                    </div>

                </div>
            </div>
        </form>
    </div>
</div>



@section scripts{
    <script src=@Url.Content("~/Scripts/Dashboard/VendorPayment/VendorPaymentEdit.js")></script>
}